services:
    postgres:
        image: postgres:17.2
        container_name: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        name: postgres_data
